name: Deploy

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Setup Checkout
      uses: actions/checkout@v3
      
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: build image
      run: docker build -t squib0612/sinsahelper-frontend:latest .
      
    - name: push image to hub
      run: docker push squib0612/sinsahelper-frontend:latest
